# Generated by Django 5.0 on 2024-05-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('images', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
