# Generated by Django 5.0 on 2024-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_year_usersubmission_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='alternativa_a',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alternativa_b',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alternativa_c',
            field=models.CharField(default=22, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alternativa_d',
            field=models.CharField(default=33, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alternativa_e',
            field=models.CharField(default=33, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='resposta_correta',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
