# Generated by Django 5.0 on 2024-05-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_usersubmission_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='categoria_bloom',
            field=models.CharField(choices=[('KN', 'Conhecimento'), ('CO', 'Compreensão'), ('AP', 'Aplicação'), ('AN', 'Análise'), ('SY', 'Síntese'), ('EV', 'Avaliação'), ('NP', 'Não faz parte da taxonomia')], default='NP', max_length=2),
        ),
    ]
