# Generated by Django 5.0 on 2024-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_usersubmission_componentes_curriculares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='componentes_curriculares',
            field=models.TextField(),
        ),
    ]
