# Generated by Django 5.0 on 2024-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_usersubmission_componentes_curriculares'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
